app:
    resource: '@AppBundle/Controller/'
    type: annotation

home_page:
    path: /
    defaults: { _controller: AppBundle:Default:home }

login_page:
    path: /login
    defaults: { _controller: AppBundle:Default:login }

contact_page:
    path: /contact
    defaults: { _controller: AppBundle:Default:contact }

games_page:
    path: /games
    defaults: { _controller: AppBundle:Default:games }
