app:
    resource: '@AppBundle/Controller/'
    type: annotation

home_page:
    path: /
    defaults: { _controller: AppBundle:Default:home }

login_page:
    path: /login
    defaults: { _controller: AppBundle:Default:login }
